# Generated by Django 6.0.7 on 2026-08-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_employee_id'),
        ('tasks', '0014_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, help_text='Set when an Admin approved this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by_employee',
            field=models.ForeignKey(blank=True, help_text='Set when a TL approved this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewed_as_tl', to='accounts.employee'),
        ),
    ]
