# Generated by Django 6.0.7 on 2026-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_reviewed_by_admin_task_reviewed_by_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Task Created'), ('assigned', 'Assigned / Reassigned'), ('started', 'Timer Started'), ('paused', 'Timer Paused'), ('resumed', 'Timer Resumed'), ('submitted', 'Submitted'), ('review_started', 'Review Started'), ('approved', 'Approved'), ('rework_requested', 'Rework Requested'), ('hold', 'Put On Hold'), ('released_hold', 'Hold Released'), ('cancelled', 'Cancelled'), ('correction_requested', 'Time Correction Requested'), ('correction_decided', 'Time Correction Decided')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('not_started', 'Assigned / Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rework_needed', 'Rework Needed'), ('resubmitted', 'Resubmitted'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=20),
        ),
    ]
