# Generated by Django 6.0.7 on 2026-08-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_activitylog_action_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
