# Generated by Django 6.0.7 on 2026-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmaster',
            options={'ordering': ['project_name', 'task_name']},
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
