# Generated by Django 6.0.7 on 2026-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_taskmaster_options_taskmaster_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
