# Generated by Django 6.0.7 on 2026-08-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_is_active'),
        ('tasks', '0019_task_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks_as_admin', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='timersession',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timer_sessions_as_admin', to='accounts.admin'),
        ),
        migrations.AlterField(
            model_name='timersession',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timer_sessions', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='timersession',
            name='is_rework_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='timersession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('admin__isnull', True), ('employee__isnull', False)), models.Q(('admin__isnull', False), ('employee__isnull', True)), _connector='OR'), name='timer_session_exactly_one_actor'),
        ),
    ]
