# Generated by Django 6.0.7 on 2026-08-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_is_active'),
        ('tasks', '0020_task_assigned_to_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtaskdefinition',
            name='assigned_to_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_task_definitions_as_admin', to='accounts.admin'),
        ),
        migrations.AlterField(
            model_name='recurringtaskdefinition',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_task_definitions', to='accounts.employee'),
        ),
    ]
