# Generated by Django 6.0.7 on 2026-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_recurringtaskdefinition_assigned_to_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtaskdefinition',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
