# Generated by Django 6.0.7 on 2026-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_recurringtaskdefinition_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtaskdefinition',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO date strings (YYYY-MM-DD) to skip/exclude from generation'),
        ),
    ]
