# Generated by Django 6.0.7 on 2026-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_recurringtaskdefinition_excluded_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when task becomes active', null=True),
        ),
    ]
